### PR TITLE
it works

### PR DESCRIPTION
**Pull request by MichaelZhao21**

### CODE REVIEW

**Comment by MichaelZhao21** [comment]
ahhhhhhhhhhhhhhhhhh the endpoint is diff lemme just make a new one

**Comment by MichaelZhao21** [comment]
okay its done

**Review by NickBurnett — CHANGES_REQUESTED** [review]
your change breaks single emails btw

**Comment by MichaelZhao21** [comment]
> your change breaks single emails btw

wait no i just removed JSON.parse() bc it automatically parses the JSON if u set the content-type header to application/json

**Pull request closed without merging**
